### ISSUE TITLE
[win64] UE4.26 - Rider is not listed in the engine settings -> Code

### ISSUE THREAD

**Issue by danglingptr0x0** [JetBrains/RiderSourceCodeAccess#10]
Hello,

Just tried enabling Rider for UE4.26, but it's not listed with the other entries. Only VS and CLion are there.

Tried to install the plugin from Epic's marketplace, but got a 404 instead. It isn't there.

Version: 4.26.2-15973114+++UE4+Release-4.26

Thanks

**Comment by DecoyRS** [comment]
Hello @simonSlamka

Make sure that you have "Rider for Unreal Engine" installed and not simply "Rider"

**Comment by danglingptr0x0** [comment]
That was the issue. Closed after I fixed it. Thanks.
