### ISSUE TITLE
Unreal Engine 5 - Mac Support

### ISSUE THREAD

**Issue by uzayayan** [JetBrains/RiderSourceCodeAccess#9]
Hey guys, I have problem about integration UE5 to Rider. I can't see that "Rider Source Code Access" plugin in the plugins window. How can I get it for MacOS?

**Comment by DecoyRS** [comment]
Hello @uzayayan
Clone latest version of Master branch into Game/Plugins/RiderSourceCodeAccess folder

**Comment by uzayayan** [comment]
Yes! It's working now. Thank you.

By the way I get some errors in Rider. I guess, it is known issues right?

<img width="270" alt="Screen Shot 2021-06-02 at 19 32 56" src="https://user-images.githubusercontent.com/23665649/120517664-5b2e1b80-c3d9-11eb-81f0-2141eb3d8753.png">

<img width="352" alt="Screen Shot 2021-06-02 at 19 30 43" src="https://user-images.githubusercontent.com/23665649/120517492-2f129a80-c3d9-11eb-842c-3151cebd9de6.png">

**Comment by DecoyRS** [comment]
yes, there's a known issue with Rider doesn't resolving symbols in build.cs and target.cs files for UE5 on MacOS
